export { default as Header } from './Header/Header';
export { default as Sidebar } from './Sidebar/Sidebar';
export { default as MainContent } from './MainContent/MainContent';
export { default as ProductList } from './ProductList/ProductList';
export { default as Categories } from './Categories/Cateories';
export { default as Sale } from './Sale/Sale';
export { default as Footer } from './Footer/Footer';
export { default as ProductCard } from '../pages/ProductCard/ProductCard';
export { default as Registration } from './Registration/Registration';
export { default as ProductCatalog } from './ProductCatalog/ProductCatalog';
export { default as CartProduct } from './CartProduct/CartProduct'
